name: Create package
description: Create a package with build artifacts
inputs:
  build-dir:
    description: path to the build directory
  package-name:
    description: target name of the package
runs:
  using: composite
  steps:
    - name: Create ZIP file
      shell: bash
      run: |
        echo "::group::Create ZIP file"
        # Run 'make install' on build directory
        pushd ${{ inputs.build-dir }}
        make install
        popd

        # Copy COPYING file to install directory
        cp COPYING ${{ inputs.build-dir }}/install/

        # Create ZIP file
        pushd ${{ inputs.build-dir }}
        mv install ${{ inputs.package-name }}
        zip -r ${{ inputs.package-name }} ${{ inputs.package-name }}
        popd

        # Move package to root directory
        mv ${{ inputs.build-dir }}/${{ inputs.package-name }}.zip .
        echo "::endgroup::"

    # For testing purposes:
    #- name: Upload package
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: ${{ inputs.package-name }}
    #    path: ${{ inputs.build-dir }}/${{ inputs.package-name }}.zip
