on: push

name: Build wheels

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        CIBW_BEFORE_ALL_LINUX: bash ./contrib/cibw_before_all_linux.sh

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl
