on: push

name: Build wheels

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      with:
        config-file: ./pyproject.toml
      env:
        CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_*"
        CIBW_BEFORE_ALL_LINUX: bash ./contrib/cibw_before_all_linux.sh
        CIBW_ENVIRONMENT_LINUX: CPLUS_INCLUDE_PATH="$(pwd)/install/include" LIBRARY_PATH="$(pwd)/install/lib64" LD_LIBRARY_PATH="$(pwd)/install/lib64:$LD_LIBRARY_PATH"


    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl
